### ISSUE TITLE
Reverse feature

### ISSUE THREAD

**Issue by n8er11** [ttsda/beets-noimport#1]
Per the PyPI page, attempting to reverse a folder I added earlier with the "beet -r noimport "D:\Music" command. I'm getting the following error-
Usage:
  beet-script.py COMMAND [ARGS...]
  beet-script.py help COMMAND

beet-script.py: error: no such option: -r

Is there something I need to add/edit in my config to get the reverse function working? 

All other features working great. Thank you!

**Comment by tiagoad** [comment]
Hi @n8er11, what are you attempting to do exactely?

What this plugin will do is add a file or directory to the incremental import ignore list, meaning those files will be ignored the next time you do an incremental import that would otherwise include them, it doesn't have any flags that you can use.
